- name: Create Jenkins Jobs
  hosts: localhost
  connection: local
  tasks:
    - name: Create Jenkins Jobs
      community.general.jenkins_job:
        config: "{{ lookup('file', 'test.xml') }}"
        name: test-create-from-ansible
        password: admin123
        url: http://172.31.1.102:8080
        user: admin
