- name: Copy Xml File
  ansible.builtin.template:
  src: sjob.xml
  dest: /tmp/sjob.xml

- name: Create Jenkins Jobs
  community.general.jenkins_job:
    config: "{{ lookup('file', 'sjob.xml') }}"
    name: "{{item.job_name}}"
    password: admin123
    url: http://172.31.1.102:8080
    user: admin