sjobs:
    - { git_repo_url: https://github.com/suji1211/roboshop-terraform.git,  job_name: roboshop-terraform }
    - { git_repo_url: https://github.com/suji1211/roboshop-ansible.git,  job_name: roboshop-ansible }